### ISSUE TITLE
Error: Cannot find module 'prettier-plugin-tailwindcss'

### ISSUE THREAD

**Issue by cope** [tailwindlabs/prettier-plugin-tailwindcss#100]
**What version of `prettier-plugin-tailwindcss` are you using?**

^0.1.13

**What version of Tailwind CSS are you using?**

^3.2.3

**What version of Node.js are you using?**

v18.9.0

**What package manager are you using?**

pnpm

**What operating system are you using?**

Windows

**Reproduction URL**

Not applicable

**Describe your issue**

Running prettier from the command line works fine.

But WebStorm is no longer able to run prettier, due to this error:

Error: Cannot find module 'prettier-plugin-tailwindcss'
Require stack:
- C:\git\my-project\node_modules\.pnpm\prettier@2.7.1\node_modules\prettier\index.js
- C:\Program Files\JetBrains\WebStorm 2021.2.2\plugins\prettierJS\prettierLanguageService\prettier-plugin.js
- C:\Program Files\JetBrains\WebStorm 2021.2.2\plugins\prettierJS\prettierLanguageService\prettier-plugin-provider.js
- C:\Program Files\JetBrains\WebStorm 2021.2.2\plugins\JavaScriptLanguage\jsLanguageServicesImpl\js-language-service.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
    at resolve (node:internal/modules/cjs/helpers:109:19)
    at C:\git\my-project\node_modules\.pnpm\prettier@2.7.1\node_modules\prettier\index.js:37165:25
    at Array.map (<anonymous>)
    at Object.load (C:\git\my-project\node_modules\.pnpm\prettier@2.7.1\node_modules\prettier\index.js:37160:65)
    at Object.load [as loadPlugins] (C:\git\my-project\node_modules\.pnpm\prettier@2.7.1\node_modules\prettier\index.js:15932:23)
    at Object.getFileInfo (C:\git\my-project\node_modules\.pnpm\prettier@2.7.1\node_modules\prettier\index.js:37227:24)
    at PrettierPlugin.<anonymous> (C:\Program Files\JetBrains\WebStorm 2021.2.2\plugins\prettierJS\prettierLanguageService\prettier-plugin.js:88:58)
    at step (C:\Program Files\JetBrains\WebStorm 2021.2.2\plugins\prettierJS\prettierLanguageService\prettier-plugin.js:34:23)
    at Object.next (C:\Program Files\JetBrains\WebStorm 2021.2.2\plugins\prettierJS\prettierLanguageService\prettier-plugin.js:15:53)
Process finished with exit code -1

**Comment by adamwathan** [comment]
Hey! For help questions please use our [discussion](https://github.com/tailwindlabs/tailwindcss/discussions), we use issues exclusively for concrete bug reports.

To me the error reads like you haven’t installed the plugin, so I would install it with npm and if that doesn’t work, delete node_modules in case something got into a bad state there and reinstall your dependencies.

**Comment by cope** [comment]
If I did not install the plugin, it would not have worked from the command line. And it does.

And the plugin is installed, and reinstalled a few times along with prettier.
