### ISSUE TITLE
Plugin throws error in VS Code

### ISSUE THREAD

**Issue by AndrejGajdos** [tailwindlabs/prettier-plugin-tailwindcss#175]
**What version of `prettier-plugin-tailwindcss` are you using?**

0.3.0

**What version of Tailwind CSS are you using?**

3.3.1

**What version of Node.js are you using?**

v18.15.0

**What package manager are you using?**

npm 9.5.0

**What operating system are you using?**

macOS Ventura

**Describe your issue**

VS Code Prettier plugin throws an error, if this plugin is used.

```
["INFO" - 09:52:36] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 09:52:36] Prettier Options:
{
  "filepath": "/Users/andrejgajdos/dev/api-importer/src/utils/updateNotion.ts",
  "parser": "typescript",
  "useTabs": false,
  "tabWidth": 2,
  "printWidth": 120,
  "endOfLine": "lf",
  "arrowParens": "always",
  "bracketSpacing": true,
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": true,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": false,
  "singleQuote": true,
  "trailingComma": "es5",
  "vueIndentScriptAndStyle": false,
  "plugins": [
    {
      "options": {
        "tailwindConfig": {
          "type": "string",
          "category": "Tailwind CSS",
          "description": "TODO"
        }
      },
      "parsers": {
        "html": {
          "astFormat": "html"
        },
        "glimmer": {
          "astFormat": "glimmer"
        },
        "lwc": {
          "astFormat": "html"
        },
        "angular": {
          "astFormat": "html"
        },
        "vue": {
          "astFormat": "html"
        },
        "css": {
          "astFormat": "postcss"
        },
        "scss": {
          "astFormat": "postcss"
        },
        "less": {
          "astFormat": "postcss"
        },
        "babel": {
          "astFormat": "estree"
        },
        "babel-flow": {
          "astFormat": "estree"
        },
        "flow": {
          "astFormat": "estree"
        },
        "typescript": {
          "astFormat": "estree"
        },
        "babel-ts": {
          "astFormat": "estree"
        },
        "espree": {
          "astFormat": "estree"
        },
        "meriyah": {
          "astFormat": "estree"
        },
        "__js_expression": {
          "astFormat": "estree"
        }
      },
      "printers": {}
    }
  ]
}
["ERROR" - 09:52:36] Error formatting document.
["ERROR" - 09:52:36] parse(n,i,o={}){var v,S;let t=cI(e,o);t.astFormat==="svelte-ast"&&(o.printer=PI["svelte-ast"]);let u=t.parse(n,...<omitted>...u} could not be cloned.
DataCloneError: parse(n,i,o={}){var v,S;let t=cI(e,o);t.astFormat==="svelte-ast"&&(o.printer=PI["svelte-ast"]);let u=t.parse(n,...<omitted>...u} could not be cloned.
    at new DOMException (node:internal/per_context/domexception:72:5)
    at Worker.postMessage (node:internal/worker:343:5)
    at t.PrettierWorkerInstance.callMethod (/Users/andrejgajdos/.vscode/extensions/esbenp.prettier-vscode-9.15.0/dist/extension.js:1:17460)
    at t.PrettierWorkerInstance.format (/Users/andrejgajdos/.vscode/extensions/esbenp.prettier-vscode-9.15.0/dist/extension.js:1:17078)
    at t.default.format (/Users/andrejgajdos/.vscode/extensions/esbenp.prettier-vscode-9.15.0/dist/extension.js:1:14808)
    at t.PrettierEditProvider.provideEdits (/Users/andrejgajdos/.vscode/extensions/esbenp.prettier-vscode-9.15.0/dist/extension.js:1:11430)
    at U.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:45790)
["INFO" - 09:52:36] Formatting completed in 8ms.
```

**Comment by mahdiElmi** [comment]
I have a similar problem
it was working correctly I don't know what happened

```{
  "parser": "babel",
  "plugins": [
    {
      "options": {
        "tailwindConfig": {
          "since": "0.0.0",
          "type": "string",
          "category": "Tailwind CSS",
          "description": "Path to Tailwind configuration file"
        },
        "tailwindAttributes": {
          "since": "0.3.0",
          "type": "string",
          "array": true,
          "default": [
            {
              "value": []
            }
          ],
          "category": "Tailwind CSS",
          "description": "List of attributes/props that contain sortable Tailwind classes"
        },
        "tailwindFunctions": {
          "since": "0.3.0",
          "type": "string",
          "array": true,
          "default": [
            {
              "value": []
            }
          ],
          "category": "Tailwind CSS",
          "description": "List of functions and tagged templates that contain sortable Tailwind classes"
        }
      },
      "parsers": {
        "html": {
          "astFormat": "html"
        },
        "glimmer": {
          "astFormat": "glimmer"
        },
        "lwc": {
          "astFormat": "html"
        },
        "angular": {
          "astFormat": "html"
        },
        "vue": {
          "astFormat": "html"
        },
        "css": {
          "astFormat": "postcss"
        },
        "scss": {
          "astFormat": "postcss"
        },
        "less": {
          "astFormat": "postcss"
        },
        "babel": {
          "astFormat": "estree"
        },
        "babel-flow": {
          "astFormat": "estree"
        },
        "flow": {
          "astFormat": "estree"
        },
        "typescript": {
          "astFormat": "estree"
        },
        "babel-ts": {
          "astFormat": "estree"
        },
        "espree": {
          "astFormat": "estree"
        },
        "meriyah": {
          "astFormat": "estree"
        },
        "__js_expression": {
          "astFormat": "estree"
        }
      },
      "printers": {}
    }
  ],
  "tailwindConfig": "./styles/tailwind.config.js"
}
["ERROR" - 2:34:07 PM] Error formatting document.
["ERROR" - 2:34:07 PM] parse(a,m,f={}){let{context:s,generateRules:l}=dI(f),c=Wm(ws,e,f);c.astFormat in vv&&(f.printer=vv[c.astFormat]...<omitted>...d} could not be cloned.
DataCloneError: parse(a,m,f={}){let{context:s,generateRules:l}=dI(f),c=Wm(ws,e,f);c.astFormat in vv&&(f.printer=vv[c.astFormat]...<omitted>...d} could not be cloned.
	at new DOMException (node:internal/per_context/domexception:72:5)
	at Worker.postMessage (node:internal/worker:343:5)
	at t.PrettierWorkerInstance.callMethod (c:\Users\sholdul\.vscode\extensions\esbenp.prettier-vscode-9.15.0\dist\extension.js:1:17460)
	at t.PrettierWorkerInstance.format (c:\Users\sholdul\.vscode\extensions\esbenp.prettier-vscode-9.15.0\dist\extension.js:1:17078)
	at t.default.format (c:\Users\sholdul\.vscode\extensions\esbenp.prettier-vscode-9.15.0\dist\extension.js:1:14808)
	at async t.PrettierEditProvider.provideEdits (c:\Users\sholdul\.vscode\extensions\esbenp.prettier-vscode-9.15.0\dist\extension.js:1:11430)
	at async U.provideDocumentFormattingEdits (c:\Users\sholdul\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:101:45790)
["INFO" - 2:34:07 PM] Formatting completed in 10ms.```

**Comment by hauptrolle** [comment]
I have the same issue since the last prettier update 😢

**Comment by thecrypticace** [comment]
Hey all! What prettier version are you using? Do you have a project (it doesn't have to be minimal if that would be too difficult) that you can share that is erroring?

**Comment by mahdiElmi** [comment]
yo, a new update came for vs code plugin of prettier and it fixed it for me!

**Comment by hauptrolle** [comment]
@All can confirm, its working again. I think this issue can be closed.

@AndrejGajdos is it working for you too?

**Comment by AndrejGajdos** [comment]
@hauptrolle yes! the update of VS Code prettier plugin fixed it.
