### ISSUE TITLE
Bug: Formatting doesn't work with optional chaining in template code

### ISSUE THREAD

**Issue by tlaverdure** [tailwindlabs/prettier-plugin-tailwindcss#5]
Formatting is not working with angular templates that use the optional chaining operator.

**Vue syntax works**

```html
<button :class="{ 'test': a?.b }"> Button</button>
```

**Angular [] syntax causes an error**

```html
<button [ngClass]="{ 'test': a?.b }">Button</button>
```

<details>
  <summary>Error Output</summary>

```
Error: Line 2: Unexpected token .
    at t.constructError (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:99104)
    at t.createError (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:99323)
    at c.h.unexpectedTokenError (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:36571)
    at c.h.throwUnexpectedToken (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:36781)
    at c.h.parsePrimaryExpression (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:43621)
    at c.parsePrimaryExpression (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:42:161117)
    at c.h.inheritCoverGrammar (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:41493)
    at c.h.parseLeftHandSideExpressionAllowCall (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:54138)
    at c.h.inheritCoverGrammar (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:41493)
    at c.h.parseUpdateExpression (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:57007)
    at c.h.parseUnaryExpression (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:58391)
    at c.h.inheritCoverGrammar (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:41493)
    at c.h.parseExponentiationExpression (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:58506)
    at c.h.inheritCoverGrammar (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:41493)
    at c.h.parseBinaryExpression (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:59096)
    at c.h.inheritCoverGrammar (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:41493)
    at c.h.parseConditionalExpression (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:60031)
    at c.h.parseAssignmentExpression (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:62247)
    at c.h.isolateCoverGrammar (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:40952)
    at c.h.parseConditionalExpression (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:60178)
    at c.h.parseAssignmentExpression (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:62247)
    at c.h.inheritCoverGrammar (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:41493)
    at c.h.parseObjectProperty (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:47978)
    at c.h.parseObjectInitializer (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:48678)
    at c.h.inheritCoverGrammar (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:41493)
    at c.h.parsePrimaryExpression (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:43305)
    at c.parsePrimaryExpression (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:42:161117)
    at c.h.inheritCoverGrammar (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:41493)
    at c.h.parseLeftHandSideExpressionAllowCall (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:54138)
    at c.h.inheritCoverGrammar (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:41493)
    at c.h.parseUpdateExpression (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:57007)
    at c.h.parseUnaryExpression (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:58391)
    at c.h.inheritCoverGrammar (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:41493)
    at c.h.parseExponentiationExpression (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:58506)
    at c.h.inheritCoverGrammar (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:41493)
    at c.h.parseBinaryExpression (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:59096)
    at c.h.inheritCoverGrammar (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:41493)
    at c.h.parseConditionalExpression (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:60031)
    at c.h.parseAssignmentExpression (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:62247)
    at c.h.isolateCoverGrammar (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:40952)
    at c.h.parseLexicalBinding (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:66418)
    at c.h.parseBindingList (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:66578)
    at c.h.parseLexicalDeclaration (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:67167)
    at c.h.parseStatementListItem (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:65494)
    at c.h.parseScript (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:43:93668)
    at Object.l [as parse] (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:42:154791)
    at Object.nP [as parse] (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:49:9607)
    at Object.TP (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:58:889)
    at n (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:145:2612)
    at n (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:145:2922)
    at n (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:145:2922)
    at n (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:145:2922)
    at Object.parse (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier-plugin-tailwindcss/dist/index.js:145:2363)
    at Object.parse$d [as parse] (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier/index.js:12975:19)
    at coreFormat (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier/index.js:14525:16)
    at formatWithCursor$1 (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier/index.js:14765:14)
    at /Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier/index.js:60959:12
    at Object.Success [as format] (/Users/[REDACTED]/Sites/[REDACTED]/node_modules/prettier/index.js:60979:12)
    at t.default.<anonymous> (/Users/[REDACTED]/.vscode/extensions/esbenp.prettier-vscode-9.1.0/src/PrettierEditService.ts:435:45)
    at Generator.next (<anonymous>)
    at s (/Users/[REDACTED]/.vscode/extensions/esbenp.prettier-vscode-9.1.0/dist/extension.js:1:7872)
```
</details>

**Comment by bradlc** [comment]
Hey @tlaverdure. Which version of the plugin are you using? If you're not using the latest version (`v0.1.3`) please could you see if upgrading fixes your issue?

**Comment by tlaverdure** [comment]
Hey @bradlc, yes I'm on 0.1.3 and I'm still experiencing this issue.

**Comment by tlaverdure** [comment]
Thanks for following up @bradlc. I revisited this issue and it seems to no longer be happening on an existing project and the reproduction I was preparing 🤔 

Only thing I can think of is probably switching from Node LTS (16.x) to Node Current (17.x) recently. Anyways, problem solved in my case!
